### PR TITLE
boost as submodule, increase warning levels, allow SFINAE in type relflection

### PR DESCRIPTION
**Pull request by Manu343726**

### CODE REVIEW

**Comment by Manu343726** [comment]
BTW I forgot to update the build instructions in the README, to refer to the new variable and remove the old ones.

**Comment by flexferrum** [comment]
You can do it with PR regarded to gcc 7 build error fix.

**Comment by Manu343726** [comment]
https://stackoverflow.com/a/21756517/1609356 Pffff

**Comment by Manu343726** [comment]
> You can do it with PR regarded to gcc 7 build error fix.

to the boost_submodule branch, right?

**Comment by flexferrum** [comment]
I wonder if there is a way to suppress warnings in third-party headers. I heard there is. Something connected with 'system headers' command line option. But I'm not completely sure.

https://stackoverflow.com/questions/1867065/how-to-suppress-gcc-warnings-from-library-headers

https://cmake.org/cmake/help/v3.0/command/include_directories.html

Try to prefix boost include path with 'SYSTEM' in CMakeLists.txt

**Comment by flexferrum** [comment]
> to the boost_submodule branch, right

Defenetely.

**Comment by Manu343726** [comment]
I have no control of the boost targets, and I would not like to touch anything from there..., so I've disabled the error (The warning is still there).

**Comment by flexferrum** [comment]
I see. OK.

**Comment by flexferrum** [comment]
I think, I'll replace it win optional-lite in some future.

**Comment by Manu343726** [comment]
[cppfs](https://github.com/cginternals/cppfs) is a good replacement for boost::filesystem

**Comment by flexferrum** [comment]
Thanks. I'll think about it.

**Pull request merged**
