### PR TITLE
boost as submodule, increase warning levels, allow SFINAE in type relflection

### PR DESCRIPTION
**Pull request by Manu343726**
See #38

### CODE REVIEW

**Comment by Manu343726** [comment]
Some notes:

 - Now all dependencies are built in-source, as part of your CMake project.
 - I've tried to keep the boost config the same, but I'm not sure if some config vares related to the runtime would work.
 - Boost is always statically linked. Since we're linking against a couple of small libs, this is not a problem (Check the build logs).
 - `WITH_TESTS` variable changed to a `JINJA2CPP_BUILD_TESTS` option, to avoid ambiguities.
 - CMake already has a standard `BUILD_SHARED_LIBS` variable to control if libs are shared or static by default.

**Comment by flexferrum** [comment]
-DJINJA2CPP_BUILD_TESTS=1 option need to be added to travis/appveyor files.

**Comment by Manu343726** [comment]
The variable initialization was broken, it should be TRUE by default if jinja2cpp is the main project

**Comment by flexferrum** [comment]
It's the static/dynamic MSVC runtime hell...

**Comment by flexferrum** [comment]
Actually, you can focus only on gcc 7 issue. MSVC issue I'll fix by myself.

**Comment by Manu343726** [comment]
Great! I don't have any MSVC installation right now in any of my PCs...

**Comment by flexferrum** [comment]
May it will be a good idea to make this pull request into separate branch in order to keep master green. And when I fix MSVC issues I'll merge it to the master.

**Comment by Manu343726** [comment]
Right. Tell me the branch and I will send the PR there

**Comment by flexferrum** [comment]
Branch for this PR: https://github.com/flexferrum/Jinja2Cpp/tree/boost_submodule

**Comment by Manu343726** [comment]
https://github.com/flexferrum/Jinja2Cpp/pull/54

**Pull request closed without merging**
